service:
  name: test

plugins:
  - serverless-glob-merge-yaml

provider:
  name: aws
  variableSyntax: "\\${([ *+|~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}"

resources:
  # Note: This isn't valid cloudformation, but it serves well to test variable resolution.
  resourcesCase: ${glob-merge-yaml:src/**/serverless.yml:resources}
  functionsCase: ${glob-merge-yaml:src/**/serverless.yml:functions}
  envCase: ${glob-merge-yaml:env/*+(after|default|${opt:stage,'dev'}).yml}
  iamRoleStatementsCase: ${glob-merge-yaml:src/**/serverless.yml:provider.iamRoleStatements}
